# Generated by Django 3.0.7 on 2020-07-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_editor', '0001_initial'),
        ('accounts', '0003_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('file_extension', models.CharField(max_length=10)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_editor.ProgrammingLanguage')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('soft_deleted', models.BooleanField()),
                ('accessors', models.ManyToManyField(null=True, related_name='accessible_projects', to='accounts.UserAccount')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='accounts.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ProjItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('soft_deleted', models.BooleanField()),
                ('is_folder', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('file_contents', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container', to='projects.FileItem')),
                ('folder_dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_contents', to='projects.ProjItem')),
                ('root_proj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='projects.Project')),
            ],
        ),
    ]
