# Generated by Django 3.0.7 on 2020-07-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200701_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projitem',
            name='file_contents',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container', to='projects.FileItem'),
        ),
        migrations.AlterField(
            model_name='projitem',
            name='folder_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_contents', to='projects.ProjItem'),
        ),
        migrations.AlterField(
            model_name='projitem',
            name='root_proj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='projects.Project'),
        ),
    ]
