# Generated by Django 3.0.7 on 2020-08-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projitem',
            name='folder_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='projects.ProjItem'),
        ),
    ]
