# Generated by Django 3.0.7 on 2020-12-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_useraccount_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_useraccount_friends_+', to='accounts.UserAccount'),
        ),
    ]
